# name: Mirror Sync
# 
# on:
#   push:
#     branches: [ "master" ]
#   workflow_dispatch:
#   schedule:
#     - cron: "0 */8 * * *"
# 
# jobs:
#   codeberg:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
# ... (todas las l√≠neas con # al principio)
