name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete_merged_branch:
    runs-on: 'ubuntu-24.04'
    # Solo se ejecuta si la PR fue aceptada (merged) y es dentro de tu propio repo
    if: github.event.pull_request.merged == true && github.repository == github.event.pull_request.head.repo.full_name
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete branch
        run: |
          branch_name="${{ github.event.pull_request.head.ref }}"
          # Protecci√≥n extra para nunca borrar las ramas principales
          if [ "$branch_name" != "main" ] && [ "$branch_name" != "master" ] && [ "$branch_name" != "repo" ]; then
            echo "Deleting branch ${branch_name}"
            git push origin --delete "$branch_name"
          else
            echo "Skipping deletion of protected branch: ${branch_name}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
